# lakefile.toml
name = "VerifyLean"
version = "0.1.0"

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4.git", rev = "master" }

[[lean_lib]]
name = "VerifyLean"

[[lean_exe]]
name = "verifylean"
root = "Main"